### ISSUE TITLE
There is some problem with turbolinks

### ISSUE THREAD

**Issue by geekvijay** [wittawasw/zopim_rails#7]
When traversing from one page to another page, it does not maintain the state of conversion.

**Comment by luizpicolo** [comment]
Hello @geekvijay.

This is fixed #1

**Comment by geekvijay** [comment]
@luizpicolo i am checking it out but the issue is still there

**Comment by luizpicolo** [comment]
@geekvijay i created one test https://zopimrailstest.herokuapp.com/. It worked

**Comment by geekvijay** [comment]
it's kind of weird, it was not working at development but working fine at production
